########################################################################################################################
# Repo tool base settings
########################################################################################################################

[repo_docs]
enabled = true
name = "CUDAX"
project = "CUDAX"
logo = "img/logo.png"

enhanced_search_enabled = true
api_output_directory = "api"
use_fast_doxygen_conversion = true
sphinx_generate_doxygen_groups = true
sphinx_generate_doxygen_pages = true
sphinx_exclude_patterns = [
    "build",
    "tools",
    "VERSION.md",
    "source/extensions/*/docs/Overview.md",
    "source/extensions/*/docs/CHANGELOG.md",
]

# list of files from which to extract documentation.  if a directory is specified,
# it will be recursively searched.
#
# paths are relative to ${docs_root}.
#
# defaults to an empty list.
doxygen_input = [
    "../include/cuda/experimental/*.cuh",
    "../include/cuda/experimental/detail/*.cuh",
]

# Using wildcards is also supported in `doxygen_input`. Assuming there are no other `.h` files
# in the `include/carb` directory, the above may also be specified as:
# doxygen_input = [
#     "include/carb/*.h",
#     "source/examples/example.doxygen/ExampleDoxygen.h",
# ]

# doxygen allows the creation of custom commands to ease in the documentation process.
# for example, this adds a @carb_framework_overview command which creates a link
# to a reStructuredText document. defaults to an empty list.
#
# more information on the format can be found at:
#     https://www.doxygen.nl/manual/config.html#cfg_aliases
doxygen_aliases = [
]

# doxygen sometimes gets confused by macros. the array below allows the user to
# tell doxygen how to expand a macro. defaults to an empty list.
#
# more information on the format can be found at:
#     https://www.doxygen.nl/manual/config.html#cfg_predefined
doxygen_predefined = [
    "_CCCL_HOST",
    "_CCCL_DEVICE",
    "_CCCL_HOST_DEVICE",
    "_CCCL_FORCEINLINE",
    "_CCCL_STD_VER",
    "DOXYGEN_SHOULD_SKIP_THIS",
    "DOXYGEN_ACTIVE",
    "__device__",
    "__host__",
    "__forceinline__",
    "__declspec(x)=",
    "__align__(x)=",
    "_LIBCUDACXX_CPO_ACCESSIBILITY",
]

# make sure to use ./fetch_imgs.sh
doxygen_conf_extra = """
  IMAGE_PATH             = ${config_root}/img
  DOXYFILE_ENCODING      = UTF-8
  INPUT_ENCODING         = UTF-8
  EXTENSION_MAPPING      = cuh=c++ cu=c++
  EXAMPLE_PATH           = ../examples/device
  EXAMPLE_RECURSIVE      = NO
  EXAMPLE_PATTERNS       = *.cu
  EXCLUDE_SYMBOLS        = "*detail*"
  AUTOLINK_SUPPORT       = YES
  INLINE_INHERITED_MEMB  = YES
"""
